global:
  evaluation_interval: 30s
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
- job_name: otel-collector
  static_configs:
  - targets: ["otel-collector:8888"]  
  - targets: ["otel-collector:8889"]