version: '3'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

networks:
  default:
    name: opentelemetry-demo
    driver: bridge

services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "8080:8000"
    environment:
      - ENV_PORT=8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  otel-collector:
    container_name: otel-collector
    build:
      context: ./collector
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          memory: 125M
    command: [ "--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP over gRPC receiver
      - "4318:4318" # OTLP over HTTP receiver
    logging: *logging
    depends_on:
      - prometheus 

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "9090:9090"
    logging: *logging